#! /bin/bash

#
# chext
#
# Change the extension of a file.
#
# usage: chext foo.bar baz
#
# Moves foo.bar to foo.baz.
#

vflag=""
iflag=""
# Process command line arguments
while getopts "vi" opt
do
  case "$opt" in
  -v)
    vflag="-v"
    ;;
  -i)
    iflag="-i"
    ;;
  esac
done

shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# Usage statement
if [[ $# -lt 2 ]]
then
  (>&2 echo "usage: chext [-i] [-v] source ... extension")
  exit 1
fi

# Get the last argument (i.e., the extension)
for ext
do
  true
done

while [[ $# -ge 2 ]]
do
  errmsg_noext="chext: change extension of $1 to $ext: File has no extension"
  errmsg_nofile="chext: change extension of $1 to $ext: No such file"

  # Check to see if the file exists
  if [ ! -e $1 ]
  then
    (>&2 echo "$errmsg_nofile")
  fi

  # Check to see if the file has a "." in it
  if [[ ! $1 =~ .*\..* ]]
  then
    (>&2 echo "$errmsg_noext")
  fi  

  # Check to see if the file is hidden and has no extension
  if [ -z ${1%\.*} ]
  then
    (>&2 echo "$errmsg_noext")
  fi

  # Change the extension
  mv $vflag $iflag $1 ${1%\.*}.$ext
  shift
done
